# Air configuration file
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ."
bin = "tmp/main"
full_bin = "sh -c 'tmp/main'"

[watcher]
extensions = ["go"]
exclude_dirs = ["tmp", "vendor"]
